/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/leaderboards/': RouteRecordInfo<
      '/leaderboards/',
      '/leaderboards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/leaderboards/[board_id]': RouteRecordInfo<
      '/leaderboards/[board_id]',
      '/leaderboards/:board_id',
      { board_id: ParamValue<true> },
      { board_id: ParamValue<false> },
      | '/leaderboards/[board_id]/categories/[cat_id]'
      | '/leaderboards/[board_id]/categories/[cat_id].edit'
      | '/leaderboards/[board_id]/categories/create'
    >,
    '/leaderboards/[board_id]/categories/[cat_id]': RouteRecordInfo<
      '/leaderboards/[board_id]/categories/[cat_id]',
      '/leaderboards/:board_id/categories/:cat_id',
      { board_id: ParamValue<true>, cat_id: ParamValue<true> },
      { board_id: ParamValue<false>, cat_id: ParamValue<false> },
      | never
    >,
    '/leaderboards/[board_id]/categories/[cat_id].edit': RouteRecordInfo<
      '/leaderboards/[board_id]/categories/[cat_id].edit',
      '/leaderboards/:board_id/categories/:cat_id/edit',
      { board_id: ParamValue<true>, cat_id: ParamValue<true> },
      { board_id: ParamValue<false>, cat_id: ParamValue<false> },
      | never
    >,
    '/leaderboards/[board_id]/categories/create': RouteRecordInfo<
      '/leaderboards/[board_id]/categories/create',
      '/leaderboards/:board_id/categories/create',
      { board_id: ParamValue<true> },
      { board_id: ParamValue<false> },
      | never
    >,
    '/leaderboards/[board_id].edit': RouteRecordInfo<
      '/leaderboards/[board_id].edit',
      '/leaderboards/:board_id/edit',
      { board_id: ParamValue<true> },
      { board_id: ParamValue<false> },
      | never
    >,
    '/leaderboards/create': RouteRecordInfo<
      '/leaderboards/create',
      '/leaderboards/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/[user_id]': RouteRecordInfo<
      '/users/[user_id]',
      '/users/:user_id',
      { user_id: ParamValue<true> },
      { user_id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/leaderboards/index.vue': {
      routes:
        | '/leaderboards/'
      views:
        | never
    }
    'src/pages/leaderboards/[board_id].vue': {
      routes:
        | '/leaderboards/[board_id]'
        | '/leaderboards/[board_id]/categories/[cat_id]'
        | '/leaderboards/[board_id]/categories/[cat_id].edit'
        | '/leaderboards/[board_id]/categories/create'
      views:
        | 'default'
    }
    'src/pages/leaderboards/[board_id]/categories/[cat_id].vue': {
      routes:
        | '/leaderboards/[board_id]/categories/[cat_id]'
      views:
        | never
    }
    'src/pages/leaderboards/[board_id]/categories/[cat_id].edit.vue': {
      routes:
        | '/leaderboards/[board_id]/categories/[cat_id].edit'
      views:
        | never
    }
    'src/pages/leaderboards/[board_id]/categories/create.vue': {
      routes:
        | '/leaderboards/[board_id]/categories/create'
      views:
        | never
    }
    'src/pages/leaderboards/[board_id].edit.vue': {
      routes:
        | '/leaderboards/[board_id].edit'
      views:
        | never
    }
    'src/pages/leaderboards/create.vue': {
      routes:
        | '/leaderboards/create'
      views:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
    }
    'src/pages/users/[user_id].vue': {
      routes:
        | '/users/[user_id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
